#!/usr/bin/env bash
# One-command Nintendo Switch build for UnleashedRecomp.
#
# Run from an MSYS2 shell. See docs/BUILDING-SWITCH.md for full details.
#
# Prerequisites:
#   - devkitPro + devkitA64            (DEVKITPRO, default /opt/devkitpro)
#   - MSYS2 CLANGARM64: clang cmake ninja
#   - MSYS2 CLANG64:    clang          (only for the x64 shader tool; see NOTE)
#
# Inputs you supply (kept out of the repo):
#   - Game files in UnleashedRecompLib/private/ : default.xex, default.xexp, shader.ar
#   - NVK Vulkan driver: NVK_ROOT -> any of
#         a mesa-switch tree built with its Docker build-switch.sh
#             (builddir-switch/src/nouveau/vulkan/libvulkan.a)
#         a mesa-switch tree built with build-unified.sh (MSYS2)
#             (mesa-unified-install/opt/devkitpro/portlibs/switch/lib/libvulkan.a)
#         an extracted Mesa Switch SDK, its install root or its portlibs/switch folder
#             (lib/libvulkan.a + include/vulkan)
#     See docs/SWITCH-MESA.md to build the driver with the nfsmw-nx improvements.
#
# Usage:
#   NVK_ROOT=/c/path/to/mesa-nvk  tools/build-switch.sh
#
# Performance switches (see docs/SWITCH-PERFORMANCE.md):
#   SWITCH_DIRECT_CALLS=1  (default) rewrite calls between recompiled functions so GCC can inline them
#   SWITCH_LTO=0           (default) set to 1 for link-time optimisation (needs a lot of build RAM)
#   SWITCH_LTO_JOBS=2      parallel LTRANS jobs when SWITCH_LTO=1
#   SWITCH_PGO=            empty (default), "generate" (instrumented build, no LTO) or "use"
#   SWITCH_PGO_DIR=pgo     folder with the .gcda files copied from the pgo folder next to the NRO
#   SWITCH_RECOMP_O2=0     set to 1 to A/B -O2 instead of -O3 for the recompiled code
#   SWITCH_O2=0            set to 1 to compile all the code with -O2 instead of -O3
#   SWITCH_IPA_PTA=0       set to 1 to compile and link with -fipa-pta (whole-program points-to analysis at the LTO link)
#   SWITCH_LEAF_LOCALS=0   set to 1: leaf functions keep the context's registers in locals (tools/switch-codegen-pass.py)
#   SWITCH_WIDE_DFORM=0    set to 1: register + displacement loads and stores as 64-bit addresses (same; needs the
#                          guard page kernel/memory.cpp reserves)
#   SWITCH_CONST_VMX_TABLES=0  set to 1: VMX byte-order tables as constants, table shuffles as NEON TBL (same)
#   SWITCH_NARROW_BARRIER=0    set to 1: loop barriers on guest memory only (same)
#   SWITCH_INLINE_FP_COMPARE=0 set to 1: the floating-point compare branchless and always inlined (same; a define only)
#   SWITCH_INLINE_MEMCPY=0 set to 1: guest memcpy/memset calls with a constant size as inline builtins, the other
#                          memcpy/memmove/memset calls straight to the C library (same)
#                          Functions with double-precision or vector floating-point arithmetic keep XenonRecomp's code.
#   SWITCH_EXPLICIT_FMA=0  set to 1: the guest's fused multiply-adds as explicit fused operations and everything compiled
#                          with -ffp-contract=off, so every guest operation rounds as on the Xbox 360 and no code
#                          generation option can move a rounding; the codegen pass then also handles the floating-point
#                          functions (XENON_RECOMP_EXPLICIT_FMA; recompiler.h)
#   SWITCH_SCALAR_RSQRT=0  set to 1: vrsqrtefp/vrefp of a dot product as one scalar operation (XENON_RECOMP_SCALAR_RSQRT)
#   SWITCH_FEWER_MODE_SWITCHES=0 1: XenonRecomp keeps a known flush mode for instructions whose result
#                          does not depend on it; 2: also an unknown one, for moves (changes the control flow of
#                          thousands of functions: for a build with a PGO profile collected with it; recompiler.h)
#   SWITCH_CLASSIC_CODEGEN=0  set to 1 to A/B the round-7 code generation: ppc/ generated as before it
#                          (volatile guest memory, all callee-saved stores, FPSCR state per block) and no
#                          hot-function section. ppc/ is regenerated whenever this or the recompiler changes.
#   SWITCH_BUILD_ID=       printed first in stderr.log (default: date, time and the options above)
#
# To reproduce a validated release shader cache instead of regenerating it:
#   SWITCH_SHADER_CACHE_OBJECT=/c/path/to/release_shader_cache.obj \
#   SWITCH_SHADER_CACHE_OBJECT_SHA256=<sha256> \
#   NVK_ROOT=/c/path/to/mesa-nvk tools/build-switch.sh
#
# NOTE: the bundled arm64 DXC emits invalid SPIR-V, so the game shader cache is
# generated by an x86_64 build of XenosRecomp driving the x64 DXC (runs under
# emulation on Windows-ARM). That is why CLANG64 is required.
set -euo pipefail

: "${DEVKITPRO:=/opt/devkitpro}"
# clangarm64 cmake resolves native Windows paths, not the msys /opt mount.
command -v cygpath >/dev/null 2>&1 && DEVKITPRO="$(cygpath -m "$DEVKITPRO")"
: "${NVK_ROOT:?Set NVK_ROOT to your mesa-switch build (builddir-switch or mesa-unified-install) or a Mesa Switch SDK folder. See docs/SWITCH-MESA.md.}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 8)}"
SWITCH_SHADER_CACHE_OBJECT="${SWITCH_SHADER_CACHE_OBJECT:-}"
SWITCH_SHADER_CACHE_OBJECT_SHA256="${SWITCH_SHADER_CACHE_OBJECT_SHA256:-}"
SWITCH_DIRECT_CALLS="${SWITCH_DIRECT_CALLS:-1}"
SWITCH_LTO="${SWITCH_LTO:-0}"
SWITCH_LTO_JOBS="${SWITCH_LTO_JOBS:-2}"
SWITCH_PGO="${SWITCH_PGO:-}"
SWITCH_PGO_DIR="${SWITCH_PGO_DIR:-}"
SWITCH_RECOMP_O2="${SWITCH_RECOMP_O2:-0}"
SWITCH_O2="${SWITCH_O2:-0}"
SWITCH_IPA_PTA="${SWITCH_IPA_PTA:-0}"
SWITCH_CLASSIC_CODEGEN="${SWITCH_CLASSIC_CODEGEN:-0}"
export SWITCH_LEAF_LOCALS="${SWITCH_LEAF_LOCALS:-0}"
export SWITCH_WIDE_DFORM="${SWITCH_WIDE_DFORM:-0}"
export SWITCH_CONST_VMX_TABLES="${SWITCH_CONST_VMX_TABLES:-0}"
export SWITCH_NARROW_BARRIER="${SWITCH_NARROW_BARRIER:-0}"
export SWITCH_INLINE_FP_COMPARE="${SWITCH_INLINE_FP_COMPARE:-0}"
export SWITCH_INLINE_MEMCPY="${SWITCH_INLINE_MEMCPY:-0}"
SWITCH_FEWER_MODE_SWITCHES="${SWITCH_FEWER_MODE_SWITCHES:-0}"
export SWITCH_EXPLICIT_FMA="${SWITCH_EXPLICIT_FMA:-0}"
SWITCH_SCALAR_RSQRT="${SWITCH_SCALAR_RSQRT:-0}"
SWITCH_CODEGEN_PASS="leaf$SWITCH_LEAF_LOCALS-wide$SWITCH_WIDE_DFORM-tables$SWITCH_CONST_VMX_TABLES-barrier$SWITCH_NARROW_BARRIER"
# Round 12 options join the id only when set, so ppc/ folders made by round 11 builds keep their id.
[ "$SWITCH_INLINE_FP_COMPARE" = "1" ] && SWITCH_CODEGEN_PASS="$SWITCH_CODEGEN_PASS-fpcompare1"
[ "$SWITCH_INLINE_MEMCPY" = "1" ] && SWITCH_CODEGEN_PASS="$SWITCH_CODEGEN_PASS-memcpy1"
[ "$SWITCH_FEWER_MODE_SWITCHES" != "0" ] && SWITCH_CODEGEN_PASS="$SWITCH_CODEGEN_PASS-modes$SWITCH_FEWER_MODE_SWITCHES"
[ "$SWITCH_EXPLICIT_FMA" = "1" ] && SWITCH_CODEGEN_PASS="$SWITCH_CODEGEN_PASS-fma1"
[ "$SWITCH_SCALAR_RSQRT" = "1" ] && SWITCH_CODEGEN_PASS="$SWITCH_CODEGEN_PASS-rsqrt1"
if [ -z "${SWITCH_BUILD_ID:-}" ]; then
  SWITCH_BUILD_ID="$(date +%Y%m%d-%H%M)"
  [ "$SWITCH_LTO" = "1" ] && SWITCH_BUILD_ID="$SWITCH_BUILD_ID-lto"
  [ "$SWITCH_CLASSIC_CODEGEN" = "1" ] && SWITCH_BUILD_ID="$SWITCH_BUILD_ID-classic"
  [ -n "$SWITCH_PGO" ] && SWITCH_BUILD_ID="$SWITCH_BUILD_ID-pgo-$SWITCH_PGO"
  [ "$SWITCH_CODEGEN_PASS" != "leaf0-wide0-tables0-barrier0" ] && SWITCH_BUILD_ID="$SWITCH_BUILD_ID-$SWITCH_CODEGEN_PASS"
fi

if [ "$SWITCH_PGO" = "generate" ] && [ "$SWITCH_LTO" = "1" ]; then
  echo "SWITCH_PGO=generate needs SWITCH_LTO=0 (instrumented builds are not linked with LTO)." >&2
  exit 2
fi

CLANGARM64="${CLANGARM64:-/c/msys64/clangarm64/bin}"
CLANG64="${CLANG64:-/c/msys64/clang64/bin}"
CMAKE="$CLANGARM64/cmake.exe"
NINJA="$CLANGARM64/ninja.exe"
# The host tools built with that clang (XenonRecomp, x_decompress...) need its runtime DLLs
# (libc++, libunwind) when they run in steps 4 and 5. A CLANGARM64/CLANG64 shell has them on PATH;
# an MSYS shell does not, and the tools then exit without a word.
export PATH="$CLANGARM64:$PATH"
PYTHON="${PYTHON:-}"

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"
[ -n "$SWITCH_PGO_DIR" ] || SWITCH_PGO_DIR="$root_dir/pgo"

# Accept the Docker build tree, the MSYS2 unified install stage, or an SDK folder. For the SDK
# layouts NVK_ROOT becomes the portlibs/switch folder, whose include/ has the Vulkan headers.
NVK_LIB=""
for nvk_candidate_root in \
    "$NVK_ROOT" \
    "$NVK_ROOT/opt/devkitpro/portlibs/switch" \
    "$NVK_ROOT/mesa-unified-install/opt/devkitpro/portlibs/switch"; do
  if [ -f "$nvk_candidate_root/lib/libvulkan.a" ]; then
    NVK_ROOT="$nvk_candidate_root"
    NVK_LIB="$nvk_candidate_root/lib/libvulkan.a"
    break
  fi
done
if [ -z "$NVK_LIB" ]; then
  NVK_LIB="$NVK_ROOT/builddir-switch/src/nouveau/vulkan/libvulkan.a"
fi
DXC_X64="$root_dir/tools/XenosRecomp/thirdparty/dxc-bin/bin/x64"

log() { echo; echo "==== $* ===="; }

# ---------------------------------------------------------------- preconditions
for f in default.xex default.xexp shader.ar; do
  [ -f "UnleashedRecompLib/private/$f" ] || { echo "Missing UnleashedRecompLib/private/$f (copy from your game dump)." >&2; exit 2; }
done
[ -f "$NVK_LIB" ] || { echo "NVK driver not found under NVK_ROOT=$NVK_ROOT (looked for lib/libvulkan.a, opt/devkitpro/portlibs/switch/lib/libvulkan.a, mesa-unified-install/... and builddir-switch/src/nouveau/vulkan/libvulkan.a)." >&2; exit 2; }
echo "NVK driver: $NVK_LIB"
[ -z "$SWITCH_SHADER_CACHE_OBJECT" ] || [ -f "$SWITCH_SHADER_CACHE_OBJECT" ] || {
  echo "Shader-cache object not found: $SWITCH_SHADER_CACHE_OBJECT" >&2
  exit 2
}
[ -x "$CMAKE" ] || { echo "cmake not found at $CMAKE (install MSYS2 clangarm64 cmake)." >&2; exit 2; }
if [ -z "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  [ -x "$CLANG64/clang.exe" ] || { echo "clang64 not found at $CLANG64 (pacman -S mingw-w64-clang-x86_64-clang)." >&2; exit 2; }
fi
if [ -z "$SWITCH_SHADER_CACHE_OBJECT" ] || [ "$SWITCH_DIRECT_CALLS" = "1" ]; then
  if [ -z "$PYTHON" ]; then
    if command -v python3 >/dev/null 2>&1; then
      PYTHON=python3
    elif [ -x /mingw64/bin/python.exe ]; then
      PYTHON=/mingw64/bin/python.exe
    elif command -v python >/dev/null 2>&1; then
      PYTHON=python
    else
      echo "Python is required to validate generated shaders and for SWITCH_DIRECT_CALLS." >&2
      exit 2
    fi
  fi
  command -v "$PYTHON" >/dev/null 2>&1 || [ -x "$PYTHON" ] || {
    echo "Python was not found: $PYTHON" >&2
    exit 2
  }
fi

# ------------------------------------------------------------- 1. apply patches
log "1/7 apply submodule patches"
apply_patch() { # $1 submodule dir, $2... patch files applied in order after one reset
  local dir="$1"; shift
  local stamp="$root_dir/build/patch-stamps/$(echo "$dir" | tr '/' '_').stamp"
  ( cd "$dir" 2>/dev/null || exit 0
    # When the submodule holds exactly what these patches produced last time, its files are left
    # alone: rewriting them gave them new timestamps, which rebuilt the host tools and plume and made
    # CMake regenerate ppc/ on every build.
    local patches_id diff_id
    patches_id="$(for name in "$@"; do cat "$root_dir/patches/$name" 2>/dev/null; done | sha256sum | cut -c1-64)"
    diff_id="$(git diff | sha256sum | cut -c1-64)"
    if [ -f "$stamp" ] && [ "$(sed -n 1p "$stamp")" = "$patches_id" ] && [ "$(sed -n 2p "$stamp")" = "$diff_id" ]; then
      echo "  $dir: patches already applied"
      exit 0
    fi
    git checkout -- . 2>/dev/null
    for name in "$@"; do
      local p="$root_dir/patches/$name"
      [ -f "$p" ] || continue
      if   git apply --check "$p" 2>/dev/null; then git apply "$p"; echo "  applied $name"
      elif git apply --ignore-whitespace "$p" 2>/dev/null; then echo "  applied $name (ws)"
      else echo "  WARNING: $name did not apply cleanly" >&2; fi
    done
    mkdir -p "$(dirname "$stamp")"
    { echo "$patches_id"; git diff | sha256sum | cut -c1-64; } > "$stamp" )
}
apply_patch thirdparty/plume/contrib/volk volk.patch
apply_patch thirdparty/plume              plume.patch plume-switch-perf.patch
apply_patch thirdparty/imgui              imgui.patch
apply_patch thirdparty/implot             implot.patch
apply_patch thirdparty/concurrentqueue    concurrentqueue.patch
apply_patch tools/XenonRecomp             XenonRecomp.patch
apply_patch tools/XenosRecomp             XenosRecomp-mingw-dxc.patch XenosRecomp-switch-perf.patch

# --------------------------------------------------- 2. host tools (arm64, native)
log "2/7 build host tools (arm64)"
CC="$CLANGARM64/clang.exe" CXX="$CLANGARM64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools -G Ninja -DCMAKE_BUILD_TYPE=Release \
  -DUNLEASHED_RECOMP_HOST_TOOLS_ONLY=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
"$CMAKE" --build build/host-tools -j"$JOBS" --target XenonRecomp file_to_c x_decompress

# ---------------------------- 3. host tool XenosRecomp (x86_64 cross, for x64 DXC)
log "3/7 build XenosRecomp (x64, for x64 DXC)"
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  echo "  skipped because a validated prebuilt shader-cache object was supplied"
else
  PATH="$CLANG64:$DXC_X64:$PATH" CC="$CLANG64/clang.exe" CXX="$CLANG64/clang++.exe" \
  "$CMAKE" -S . -B build/host-tools-x64 -G Ninja \
    -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=AMD64 \
    -DCMAKE_BUILD_TYPE=Release -DUNLEASHED_RECOMP_HOST_TOOLS_ONLY=ON \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
    -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
  "$CMAKE" --build build/host-tools-x64 -j"$JOBS" --target XenosRecomp
fi

# ------------------------------------------------------- 4. recompile PPC from XEX
log "4/7 recompile PPC from default.xex (+ default.xexp title update)"
# ppc/ belongs to the recompiler that wrote it (its patch), to its mode and to the TOML (functions, mid-asm
# hooks): regenerate when any of them changes. CMake never regenerates ppc/ (UnleashedRecompLib/CMakeLists.txt).
codegen_stamp="UnleashedRecompLib/ppc/codegen.txt"
codegen_id="$(cat patches/XenonRecomp.patch tools/switch-codegen-pass.py UnleashedRecompLib/config/SWA.toml 2>/dev/null | sha256sum | cut -c1-64) classic=$SWITCH_CLASSIC_CODEGEN $SWITCH_CODEGEN_PASS"
if [ -f UnleashedRecompLib/ppc/ppc_recomp.0.cpp ] && [ "$(cat "$codegen_stamp" 2>/dev/null)" != "$codegen_id" ]; then
  echo "  ppc/ was generated by another recompiler or mode; regenerating"
  # Only the generated files: the folder keeps its tracked .gitignore.
  find UnleashedRecompLib/ppc -maxdepth 1 -type f ! -name .gitignore -delete
fi
if [ ! -f UnleashedRecompLib/ppc/ppc_recomp.0.cpp ]; then
  mkdir -p UnleashedRecompLib/ppc # XenonRecomp does not create it
  XENON_RECOMP_CLASSIC="$SWITCH_CLASSIC_CODEGEN" XENON_RECOMP_FEWER_MODE_SWITCHES="$SWITCH_FEWER_MODE_SWITCHES" \
  XENON_RECOMP_EXPLICIT_FMA="$SWITCH_EXPLICIT_FMA" XENON_RECOMP_SCALAR_RSQRT="$SWITCH_SCALAR_RSQRT" \
  build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe \
    UnleashedRecompLib/config/SWA.toml tools/XenonRecomp/XenonUtils/ppc_context.h
  [ -f UnleashedRecompLib/ppc/ppc_recomp.0.cpp ] || { echo "XenonRecomp wrote no code to UnleashedRecompLib/ppc" >&2; exit 1; }
  # Round 11 code generation options, on XenonRecomp's own output (it refuses a second run on the same ppc/).
  "$PYTHON" tools/switch-codegen-pass.py || exit 1
  echo "$codegen_id" > "$codegen_stamp"
else echo "  ppc/ already generated (delete UnleashedRecompLib/ppc to regenerate)"; fi

if [ "$SWITCH_DIRECT_CALLS" = "1" ]; then
  # Idempotent: undoes its previous run first, so new hooks are picked up. The classic A/B build keeps
  # every definition a plain one (no .text.hot section).
  SWITCH_HOT_FUNCTIONS="$([ "$SWITCH_CLASSIC_CODEGEN" = "1" ] && echo 0 || echo 1)" \
  "$PYTHON" tools/switch-direct-calls.py
else
  [ -f UnleashedRecompLib/ppc/direct_calls.txt ] && "$PYTHON" tools/switch-direct-calls.py --undo
fi

# Round 15: the copies of recompiled functions with their registers in locals (the audio kernels, the main-thread
# clusters) are made from this build's recompiled code, so each copy is the code of the function it replaces.
"$PYTHON" tools/switch-localize.py || exit 1

# --------------------------------------------------------- 5. generate shaders
log "5/7 generate shader cache + app shaders"
XD="build/host-tools/tools/x_decompress/x_decompress.exe"
XS="build/host-tools-x64/tools/XenosRecomp/XenosRecomp/XenosRecomp.exe"
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  echo "  using validated prebuilt shader-cache object: $SWITCH_SHADER_CACHE_OBJECT"
else
  shader_cache="UnleashedRecompLib/shader/shader_cache.cpp"
  shader_validator="tools/validate-switch-shader-cache.py"
  shader_stamp="$shader_cache.translator"
  regenerate_shader_cache=false

  # The cache holds compiled blobs, so a cache made by an older translator (for example without
  # the constant-buffer path of XenosRecomp-switch-perf.patch) looks valid. Track the inputs.
  translator_id="$(cat patches/XenosRecomp-mingw-dxc.patch patches/XenosRecomp-switch-perf.patch \
    tools/XenosRecomp/XenosRecomp/shader_common.h 2>/dev/null | "$PYTHON" -c 'import hashlib,sys; print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())')"

  if [ ! -f "$shader_cache" ]; then
    regenerate_shader_cache=true
  elif [ "$(cat "$shader_stamp" 2>/dev/null)" != "$translator_id" ]; then
    echo "  shader cache was made by a different translator; regenerating"
    regenerate_shader_cache=true
  elif ! "$PYTHON" "$shader_validator" "$shader_cache"; then
    echo "  existing shader cache is incomplete; regenerating with the fixed host tool"
    regenerate_shader_cache=true
  else
    echo "  validated shader_cache.cpp already exists"
  fi

  if $regenerate_shader_cache; then
    "$XD" UnleashedRecompLib/private/shader.ar UnleashedRecompLib/private/shader_decompressed.ar
    shader_candidate="$shader_cache.candidate"
    PATH="$CLANG64:$DXC_X64:$PATH" "$XS" UnleashedRecompLib/private \
      "$shader_candidate" tools/XenosRecomp/XenosRecomp/shader_common.h
    "$PYTHON" "$shader_validator" "$shader_candidate"
    mv -f "$shader_candidate" "$shader_cache"
    echo "$translator_id" > "$shader_stamp"
  fi
fi
bash tools/generate-switch-app-shaders.sh

# ------------------------------------------------- 6. configure + build the app
log "6/7 configure + cross-compile the Switch app"
export DEVKITPRO
shader_cache_cmake_args=()
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  shader_cache_cmake_args+=("-DUNLEASHED_RECOMP_SWITCH_SHADER_CACHE_OBJECT=$SWITCH_SHADER_CACHE_OBJECT")
  if [ -n "$SWITCH_SHADER_CACHE_OBJECT_SHA256" ]; then
    shader_cache_cmake_args+=("-DUNLEASHED_RECOMP_SWITCH_SHADER_CACHE_OBJECT_SHA256=$SWITCH_SHADER_CACHE_OBJECT_SHA256")
  fi
fi
PATH="$DEVKITPRO/devkitA64/bin:$PATH" \
"$CMAKE" -S . -B build/switch-app -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE=toolchains/switch-devkitA64.cmake -DCMAKE_BUILD_TYPE=Release \
  -DDEVKITPRO="$DEVKITPRO" \
  -DZSTD_BUILD_SHARED=OFF -DZSTD_BUILD_PROGRAMS=OFF \
  -DUNLEASHED_RECOMP_SWITCH=ON \
  -DUNLEASHED_RECOMP_SWITCH_USE_PREGENERATED_SHADERS=ON \
  -DUNLEASHED_RECOMP_SWITCH_USE_PREGENERATED_APP_SHADERS=ON \
  -DUNLEASHED_RECOMP_HOST_TOOLS_DIR="$root_dir/build/host-tools" \
  -DUNLEASHED_RECOMP_HOST_FILE_TO_C="$root_dir/build/host-tools/tools/file_to_c/file_to_c.exe" \
  -DUNLEASHED_RECOMP_HOST_X_DECOMPRESS="$root_dir/build/host-tools/tools/x_decompress/x_decompress.exe" \
  -DUNLEASHED_RECOMP_HOST_XENON_RECOMP="$root_dir/build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe" \
  -DPLUME_PLATFORM_SWITCH=ON -DPLUME_SWITCH_NVK_ROOT="$NVK_ROOT" -DPLUME_SWITCH_NVK_LIBRARY="$NVK_LIB" \
  -DUNLEASHED_RECOMP_SWITCH_LTO="$([ "$SWITCH_LTO" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_LTO_JOBS="$SWITCH_LTO_JOBS" \
  -DUNLEASHED_RECOMP_SWITCH_PGO="$SWITCH_PGO" \
  -DUNLEASHED_RECOMP_SWITCH_PGO_DIR="$SWITCH_PGO_DIR" \
  -DUNLEASHED_RECOMP_SWITCH_RECOMP_O2="$([ "$SWITCH_RECOMP_O2" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_O2="$([ "$SWITCH_O2" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_IPA_PTA="$([ "$SWITCH_IPA_PTA" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_EXPLICIT_FMA="$([ "$SWITCH_EXPLICIT_FMA" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_CLASSIC_CODEGEN="$([ "$SWITCH_CLASSIC_CODEGEN" = "1" ] && echo ON || echo OFF)" \
  -DUNLEASHED_RECOMP_SWITCH_BUILD_ID="$SWITCH_BUILD_ID" \
  "${shader_cache_cmake_args[@]}" \
  -DCMAKE_MAKE_PROGRAM="$NINJA"
# SWITCH_FIRST_TARGETS="obj1 obj2...": build these ninja targets (e.g. object files of hand-edited sources) first, so
# that their compile errors show up before the long compile of the recompiled code.
if [ -n "${SWITCH_FIRST_TARGETS:-}" ]; then
  PATH="$DEVKITPRO/devkitA64/bin:$PATH" "$CMAKE" --build build/switch-app -j"$JOBS" --target $SWITCH_FIRST_TARGETS
fi
PATH="$DEVKITPRO/devkitA64/bin:$PATH" "$CMAKE" --build build/switch-app -j"$JOBS" --target UnleashedRecomp

if [ "$SWITCH_DIRECT_CALLS" = "1" ]; then
  # Every sub_X in the ELF that is not an alias of its __imp__sub_X body is a hook; none of them may have
  # been called directly.
  "$PYTHON" tools/switch-direct-calls.py --verify-elf build/switch-app/UnleashedRecomp/UnleashedRecomp \
    --nm "$DEVKITPRO/devkitA64/bin/aarch64-none-elf-nm"
fi

# ------------------------------------------------------------------ 7. package
log "7/7 package NRO"
DEVKITPRO="$DEVKITPRO" bash tools/package-switch-nro.sh

echo; echo "==== Switch build complete: dist/switch/UnleashedRecomp.nro ===="
