#!/usr/bin/env bash
# One-command Nintendo Switch build for UnleashedRecomp.
#
# Run from an MSYS2 shell. See docs/BUILDING-SWITCH.md for full details.
#
# Prerequisites:
#   - devkitPro + devkitA64            (DEVKITPRO, default /opt/devkitpro)
#   - MSYS2 CLANGARM64: clang cmake ninja
#   - MSYS2 CLANG64:    clang          (only for the x64 shader tool; see NOTE)
#
# Inputs you supply (kept out of the repo):
#   - Game files in UnleashedRecompLib/private/ : default.xex, default.xexp, shader.ar
#   - NVK Vulkan driver: NVK_ROOT -> extracted mesa build dir containing
#         builddir-switch/src/nouveau/vulkan/libvulkan.a  (closed/unshipped)
#
# Usage:
#   NVK_ROOT=/c/path/to/mesa-nvk  tools/build-switch.sh
#
# To reproduce a validated release shader cache instead of regenerating it:
#   SWITCH_SHADER_CACHE_OBJECT=/c/path/to/release_shader_cache.obj \
#   SWITCH_SHADER_CACHE_OBJECT_SHA256=<sha256> \
#   NVK_ROOT=/c/path/to/mesa-nvk tools/build-switch.sh
#
# NOTE: the bundled arm64 DXC emits invalid SPIR-V, so the game shader cache is
# generated by an x86_64 build of XenosRecomp driving the x64 DXC (runs under
# emulation on Windows-ARM). That is why CLANG64 is required.
set -euo pipefail

: "${DEVKITPRO:=/opt/devkitpro}"
# clangarm64 cmake resolves native Windows paths, not the msys /opt mount.
command -v cygpath >/dev/null 2>&1 && DEVKITPRO="$(cygpath -m "$DEVKITPRO")"
: "${NVK_ROOT:?Set NVK_ROOT to your extracted mesa-nvk dir (contains builddir-switch/src/nouveau/vulkan/libvulkan.a).}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 8)}"
SWITCH_SHADER_CACHE_OBJECT="${SWITCH_SHADER_CACHE_OBJECT:-}"
SWITCH_SHADER_CACHE_OBJECT_SHA256="${SWITCH_SHADER_CACHE_OBJECT_SHA256:-}"

CLANGARM64="${CLANGARM64:-/c/msys64/clangarm64/bin}"
CLANG64="${CLANG64:-/c/msys64/clang64/bin}"
CMAKE="$CLANGARM64/cmake.exe"
NINJA="$CLANGARM64/ninja.exe"
PYTHON="${PYTHON:-}"

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

NVK_LIB="$NVK_ROOT/builddir-switch/src/nouveau/vulkan/libvulkan.a"
DXC_X64="$root_dir/tools/XenosRecomp/thirdparty/dxc-bin/bin/x64"

log() { echo; echo "==== $* ===="; }

# ---------------------------------------------------------------- preconditions
for f in default.xex default.xexp shader.ar; do
  [ -f "UnleashedRecompLib/private/$f" ] || { echo "Missing UnleashedRecompLib/private/$f (copy from your game dump)." >&2; exit 2; }
done
[ -f "$NVK_LIB" ] || { echo "NVK driver not found: $NVK_LIB" >&2; exit 2; }
[ -z "$SWITCH_SHADER_CACHE_OBJECT" ] || [ -f "$SWITCH_SHADER_CACHE_OBJECT" ] || {
  echo "Shader-cache object not found: $SWITCH_SHADER_CACHE_OBJECT" >&2
  exit 2
}
[ -x "$CMAKE" ] || { echo "cmake not found at $CMAKE (install MSYS2 clangarm64 cmake)." >&2; exit 2; }
if [ -z "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  [ -x "$CLANG64/clang.exe" ] || { echo "clang64 not found at $CLANG64 (pacman -S mingw-w64-clang-x86_64-clang)." >&2; exit 2; }
fi
if [ -z "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  if [ -z "$PYTHON" ]; then
    if command -v python3 >/dev/null 2>&1; then
      PYTHON=python3
    elif [ -x /mingw64/bin/python.exe ]; then
      PYTHON=/mingw64/bin/python.exe
    elif command -v python >/dev/null 2>&1; then
      PYTHON=python
    else
      echo "Python is required to validate generated shaders." >&2
      exit 2
    fi
  fi
  command -v "$PYTHON" >/dev/null 2>&1 || [ -x "$PYTHON" ] || {
    echo "Python was not found: $PYTHON" >&2
    exit 2
  }
fi

# ------------------------------------------------------------- 1. apply patches
log "1/7 apply submodule patches"
apply_patch() { # $1 patch file, $2 submodule dir
  local p="$root_dir/patches/$1"
  [ -f "$p" ] || return 0
  ( cd "$2" 2>/dev/null || exit 0
    git checkout -- . 2>/dev/null
    if   git apply --check "$p" 2>/dev/null; then git apply "$p"; echo "  applied $1"
    elif git apply --ignore-whitespace "$p" 2>/dev/null; then echo "  applied $1 (ws)"
    else echo "  WARNING: $1 did not apply cleanly" >&2; fi )
}
apply_patch volk.patch                    thirdparty/plume/contrib/volk
apply_patch plume.patch                   thirdparty/plume
apply_patch imgui.patch                   thirdparty/imgui
apply_patch implot.patch                  thirdparty/implot
apply_patch concurrentqueue.patch         thirdparty/concurrentqueue
apply_patch XenonRecomp.patch             tools/XenonRecomp
apply_patch XenosRecomp-mingw-dxc.patch   tools/XenosRecomp

# --------------------------------------------------- 2. host tools (arm64, native)
log "2/7 build host tools (arm64)"
CC="$CLANGARM64/clang.exe" CXX="$CLANGARM64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools -G Ninja -DCMAKE_BUILD_TYPE=Release \
  -DUNLEASHED_RECOMP_HOST_TOOLS_ONLY=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
"$CMAKE" --build build/host-tools -j"$JOBS" --target XenonRecomp file_to_c x_decompress

# ---------------------------- 3. host tool XenosRecomp (x86_64 cross, for x64 DXC)
log "3/7 build XenosRecomp (x64, for x64 DXC)"
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  echo "  skipped because a validated prebuilt shader-cache object was supplied"
else
  PATH="$CLANG64:$DXC_X64:$PATH" CC="$CLANG64/clang.exe" CXX="$CLANG64/clang++.exe" \
  "$CMAKE" -S . -B build/host-tools-x64 -G Ninja \
    -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=AMD64 \
    -DCMAKE_BUILD_TYPE=Release -DUNLEASHED_RECOMP_HOST_TOOLS_ONLY=ON \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
    -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
  "$CMAKE" --build build/host-tools-x64 -j"$JOBS" --target XenosRecomp
fi

# ------------------------------------------------------- 4. recompile PPC from XEX
log "4/7 recompile PPC from default.xex (+ default.xexp title update)"
if [ ! -f UnleashedRecompLib/ppc/ppc_recomp.0.cpp ]; then
  build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe \
    UnleashedRecompLib/config/SWA.toml tools/XenonRecomp/XenonUtils/ppc_context.h
else echo "  ppc/ already generated (delete UnleashedRecompLib/ppc to regenerate)"; fi

# --------------------------------------------------------- 5. generate shaders
log "5/7 generate shader cache + app shaders"
XD="build/host-tools/tools/x_decompress/x_decompress.exe"
XS="build/host-tools-x64/tools/XenosRecomp/XenosRecomp/XenosRecomp.exe"
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  echo "  using validated prebuilt shader-cache object: $SWITCH_SHADER_CACHE_OBJECT"
else
  shader_cache="UnleashedRecompLib/shader/shader_cache.cpp"
  shader_validator="tools/validate-switch-shader-cache.py"
  regenerate_shader_cache=false

  if [ ! -f "$shader_cache" ]; then
    regenerate_shader_cache=true
  elif ! "$PYTHON" "$shader_validator" "$shader_cache"; then
    echo "  existing shader cache is incomplete; regenerating with the fixed host tool"
    regenerate_shader_cache=true
  else
    echo "  validated shader_cache.cpp already exists"
  fi

  if $regenerate_shader_cache; then
    "$XD" UnleashedRecompLib/private/shader.ar UnleashedRecompLib/private/shader_decompressed.ar
    shader_candidate="$shader_cache.candidate"
    PATH="$CLANG64:$DXC_X64:$PATH" "$XS" UnleashedRecompLib/private \
      "$shader_candidate" tools/XenosRecomp/XenosRecomp/shader_common.h
    "$PYTHON" "$shader_validator" "$shader_candidate"
    mv -f "$shader_candidate" "$shader_cache"
  fi
fi
bash tools/generate-switch-app-shaders.sh

# ------------------------------------------------- 6. configure + build the app
log "6/7 configure + cross-compile the Switch app"
export DEVKITPRO
shader_cache_cmake_args=()
if [ -n "$SWITCH_SHADER_CACHE_OBJECT" ]; then
  shader_cache_cmake_args+=("-DUNLEASHED_RECOMP_SWITCH_SHADER_CACHE_OBJECT=$SWITCH_SHADER_CACHE_OBJECT")
  if [ -n "$SWITCH_SHADER_CACHE_OBJECT_SHA256" ]; then
    shader_cache_cmake_args+=("-DUNLEASHED_RECOMP_SWITCH_SHADER_CACHE_OBJECT_SHA256=$SWITCH_SHADER_CACHE_OBJECT_SHA256")
  fi
fi
PATH="$DEVKITPRO/devkitA64/bin:$PATH" \
"$CMAKE" -S . -B build/switch-app -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE=toolchains/switch-devkitA64.cmake -DCMAKE_BUILD_TYPE=Release \
  -DDEVKITPRO="$DEVKITPRO" \
  -DZSTD_BUILD_SHARED=OFF -DZSTD_BUILD_PROGRAMS=OFF \
  -DUNLEASHED_RECOMP_SWITCH=ON \
  -DUNLEASHED_RECOMP_SWITCH_USE_PREGENERATED_SHADERS=ON \
  -DUNLEASHED_RECOMP_SWITCH_USE_PREGENERATED_APP_SHADERS=ON \
  -DUNLEASHED_RECOMP_HOST_TOOLS_DIR="$root_dir/build/host-tools" \
  -DUNLEASHED_RECOMP_HOST_FILE_TO_C="$root_dir/build/host-tools/tools/file_to_c/file_to_c.exe" \
  -DUNLEASHED_RECOMP_HOST_X_DECOMPRESS="$root_dir/build/host-tools/tools/x_decompress/x_decompress.exe" \
  -DUNLEASHED_RECOMP_HOST_XENON_RECOMP="$root_dir/build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe" \
  -DPLUME_PLATFORM_SWITCH=ON -DPLUME_SWITCH_NVK_ROOT="$NVK_ROOT" -DPLUME_SWITCH_NVK_LIBRARY="$NVK_LIB" \
  "${shader_cache_cmake_args[@]}" \
  -DCMAKE_MAKE_PROGRAM="$NINJA"
PATH="$DEVKITPRO/devkitA64/bin:$PATH" "$CMAKE" --build build/switch-app -j"$JOBS" --target UnleashedRecomp

# ------------------------------------------------------------------ 7. package
log "7/7 package NRO"
DEVKITPRO="$DEVKITPRO" bash tools/package-switch-nro.sh

echo; echo "==== Switch build complete: dist/switch/UnleashedRecomp.nro ===="
